### ISSUE TITLE
SegmentedControlRenderer.OnElementPropertyChanged 

### ISSUE THREAD

**Issue by gbolahanonamusi** [alexrainman/SegmentedControl#57]
Random crash:

`
Xamarin caused by: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object.
  at SegmentedControl.FormsPlugin.Android.SegmentedControlRenderer.OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x00087] in <2dfd99669e8640489ce50caa541f266a>:0 
  at (wrapper delegate-invoke) <Module>:invoke_void_object_PropertyChangedEventArgs (object,System.ComponentModel.PropertyChangedEventArgs)
  at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x0000a] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:137 
  at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Element.cs:388 
  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x000f4] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:592 
  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:389 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess) [0x0005f] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:542 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value) [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:83 
  at SegmentedControl.FormsPlugin.Abstractions.SegmentedControl.set_SelectedSegment (System.Int32 value) [0x00000] in <b59e1709f8484da284c073d7a0dfea88>:0 
  at SegmentedControl.FormsPlugin.Android.SegmentedControlRenderer.NativeControl_ValueChanged (System.Object sender, Android.Widget.RadioGroup+CheckedChangeEventArgs e) [0x00095] in <2dfd99669e8640489ce50caa541f266a>:0 
  at Android.Widget.RadioGroup+IOnCheckedChangeListenerImplementor.OnCheckedChanged (Android.Widget.RadioGroup group, System.Int32 checkedId) [0x00012] in <d278c06ad5684d6882c743a94a93ebc2>:0 
  at Android.Widget.RadioGroup+IOnCheckedChangeListenerInvoker.n_OnCheckedChanged_Landroid_widget_RadioGroup_I (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_group, System.Int32 checkedId) [0x0000f] in <d278c06ad5684d6882c743a94a93ebc2>:0 
  at (wrapper dynamic-method) System.Object:7e1ebb99-18fb-41d8-a264-897860fad5fc (intptr,intptr,intptr,int)
	at mono.android.widget.RadioGroup_OnCheckedChangeListenerImplementor.n_onCheckedChanged(Native Method)
	at mono.android.widget.RadioGroup_OnCheckedChangeListenerImplementor.onCheckedChanged(RadioGroup_OnCheckedChangeListenerImplementor.java:30)
	at android.widget.RadioGroup.setCheckedId(RadioGroup.java:173)
	at android.widget.RadioGroup.-wrap0(RadioGroup.java)
	at android.widget.RadioGroup$CheckedStateTracker.onCheckedChanged(RadioGroup.java:351)
	at android.widget.CompoundButton.setChecked(CompoundButton.java:159)
	at android.widget.CompoundButton.toggle(CompoundButton.java:115)
	at android.widget.RadioButton.toggle(RadioButton.java:76)
	at android.widget.CompoundButton.performClick(CompoundButton.java:120)
	at android.view.View$PerformClick.run(View.java:21147)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
`

**Comment by alexrainman** [comment]
Fixing it in the next release.
